### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by euronay** [euronay/scrybot-mtg#1]
If anyone with some design skills would like to create an icon for MTG Wizard, it would be highly appreciated! 

I'm after a Wizard (perhaps holding a card or something) that will look at home in Google Material design style. Open to suggestions!

**Comment by euronay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Logo](https://trello.com/c/McuEE9b0/31-new-logo)

**Comment by richardbmx** [comment]
@euronay  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project.

[My Portfolio](https://www.behance.net/richardcaseres)

**Comment by euronay** [comment]
Hi @richardbmx, absolutely! Would love to see your ideas 👍

**Comment by richardbmx** [comment]
@euronay  I would like to present this idea based on the wizard you requested. the text is attached easily and as you can see it is very well dapta in any color and background, it is an image that can be easily remembered, I hope you like it if you want some change you should only request it

![NUEVO](https://user-images.githubusercontent.com/35604837/59523501-7f685900-8e9f-11e9-97c3-c9f8acf9b831.png)

**Comment by euronay** [comment]
That is really cool, @richardbmx!! Thank you so much! I'd love to use this as the logo for MTG Wizard. Can you attach a higher res version?

**Comment by richardbmx** [comment]
@euronay  perfect I love that you like it, I'm going to create a google folder with all the necessary files to use the logo, when I have it I will publish the link of the folder here

**Comment by euronay** [comment]
Brilliant! Thanks 😃

**Comment by richardbmx** [comment]
@euronay  I present here a folder of google drive with all the necessary files to use the logo within the folder you will find different variations of the logo so that you can use it in any way, additional to this there is a file that makes delivery of the copyright for that you can use the logo without problems.

[Google Drive](https://drive.google.com/open?id=1UonKGrN18oa4iw7DRYzQUwjUYkF1sc6Y)

**Comment by euronay** [comment]
Excellent thank you again! I'll update the app and the readme in the next day or so. And, of course, I will give you full credit and include the CC-by

**Comment by richardbmx** [comment]
I have made a pull requests with the incorporation of logo in the readme 

[PR](https://github.com/euronay/scrybot-mtg/pull/5)

**Comment by euronay** [comment]
Saves me a job, thanks!!

**Comment by euronay** [comment]
I've updated the logo on the Actions on Google console and updated the readme. Thanks @richardbmx!
