### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by VADS** [euronay/scrybot-mtg#3]
Hey @euronay  :) I haven't really found an email or anything else to contact you with, and you didn't answer me on twitter, so I thought I'd write you here :D A few months ago, I had an idea for "Project Atraxa" - a Google Assistant-enabled voice search for MTG card prices. I didn't really care to google if there was anything similar right away, but a few weeks later, I found your project here :) I wanted to ask if I could maybe help developing it further since there apparently haven't been any changes since ages. Do you know why MTG Wizard doesn't work on the Google Home speaker, for example?

Greeting,
Bastian (VADS)

**Comment by euronay** [comment]
Hi Bastian

Really sorry I missed your message on Twitter - but absolutely you can help! To be honest I'm surprised that anyone found it!

I was really just playing around just to explore what you could do on the home API. Unfortunately, as ever, life happens and I just kinda forgot about this. It could probably do with a bit of love as the SDK version is probably well out of date, but I'm happy to start back up on it and help out anything.

I have Trello board with some of the things I wanted to do here https://trello.com/b/NNr9a1Nl/scrybot so I can add you on that if you like - or feel free to raise issues here. Let me know your ideas!

Cheers

James 😀

**Comment by VADS** [comment]
Sure thing! I'll see if I'll be able to fork and get it working myself, I haven't really done much work with all the google stuff yet ^^

https://trello.com/basvonbassadin is my Trello profile if you wanna add me :) You can find my email here on my github profile, just throw me a message so we can communicate that way ^^

**Comment by euronay** [comment]
Good stuff. I've added you to the board and I'll drop you a mail later. I need to try and remember how all this works!
