### ISSUE TITLE
Update dependencies and fix security alerts

### ISSUE THREAD

**Issue by euronay** [euronay/scrybot-mtg#4]
All dependencies need to be updated to latest and security alerts fixed:
https://github.com/euronay/scrybot-mtg/network/alerts

**Comment by euronay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update dependencies and fix security alerts](https://trello.com/c/wxAgIgXk/35-update-dependencies-and-fix-security-alerts)

**Comment by VADS** [comment]
> https://github.com/euronay/scrybot-mtg/network/alerts

Is this a dead link or can only you as the sole contributor see it?

**Comment by euronay** [comment]
I guess only I can see it! Suppose that makes sense...
